#!/bin/sh
# Xcode Cloud runs this right after cloning, before resolving packages and building.
# Secrets.swift is git-ignored, so regenerate it here from the workflow's
# environment variables (App Store Connect > Xcode Cloud > Manage Workflows >
# <workflow> > Environment > Environment Variables).
set -e

if [ -z "$SUPABASE_URL" ] || [ -z "$SUPABASE_ANON_KEY" ]; then
    echo "error: SUPABASE_URL and SUPABASE_ANON_KEY must be set in the Xcode Cloud workflow environment" >&2
    exit 1
fi

SECRETS_PATH="$CI_PRIMARY_REPOSITORY_PATH/DebtsBook/DebtsBook/Secrets.swift"

cat > "$SECRETS_PATH" <<EOF
import Foundation

// Generated by ci_scripts/ci_post_clone.sh — do not edit.
enum Secrets {
    static let supabaseURL = URL(string: "$SUPABASE_URL")!
    static let supabaseAnonKey = "$SUPABASE_ANON_KEY"
}
EOF

echo "Generated $SECRETS_PATH"
